In [2]:
import pandas as pd
import numpy as np
import sklearn
import matplotlib.pyplot as plt
import seaborn as sns
import warnings

warnings.simplefilter(action='ignore', category=FutureWarning)

In [3]:
# Loading the ratings dataset

ratings = pd.read_csv('data1.csv')

ratings.head()

   userId  movieId  rating  timestamp
0       1        1     4.0  964982703
1       1        3     4.0  964981247
2       1        6     4.0  964982224
3       1       47     5.0  964983815
4       1       50     5.0  964982931

In [4]:
# Loading the movies dataset

movies = pd.read_csv('movies.csv')

print(movies.head())

   movieId                               title  \
0        1                    Toy Story (1995)
1        2                      Jumanji (1995)
2        3             Grumpier Old Men (1995)
3        4            Waiting to Exhale (1995)
4        5  Father of the Bride Part II (1995)

                                        genres
0  Adventure|Animation|Children|Comedy|Fantasy
1                   Adventure|Children|Fantasy
2                               Comedy|Romance
3                         Comedy|Drama|Romance
4                                       Comedy

In [10]:
# Statistical Analysis of ratings
# This means that this data is from the 'ratings' dataset

n_ratings = len(ratings)
n_movies = len(ratings['movieId'].unique())
n_users = len(ratings['userId'].unique())

print(f"Number of ratings: {n_ratings}")
print(f"Number of unique movieIds: {n_movies}")
print(f"Number of unique users: {n_users}")
print(f'Average ratings per user: {round(n_ratings/n_users, 2)}')
print(f'Average ratings per user: {round(n_ratings/n_movies, 2)}')

Number of ratings: 100836
Number of unique movieIds: 9724
Number of unique users: 610
Average ratings per user: 165.3
Average ratings per user: 10.37

In [12]:
# User rating frequency

user_freq = ratings[['userId', 'movieId']].groupby(
    'userId').count().reset_index()

user_freq.columns = ['userId', 'n_ratings']

user_freq.head()

   userId  n_ratings
0       1        232
1       2         29
2       3         39
3       4        216
4       5         44

In [13]:
# Movie Rating analysis

mean_rating = ratings.groupby('movieId')[['rating']].mean()
lowest_rated = mean_rating['rating'].idxmin()
movies.loc[movies['movieId'] == lowest_rated]
highest_rated = mean_rating['rating'].idxmax()
movies.loc[movies['movieId'] == highest_rated]


ratings[ratings['movieId'] == highest_rated]
ratings[ratings['movieId'] == lowest_rated]

movie_stats = ratings.groupby('movieId')[['rating']].agg(['count', 'mean'])

movie_stats.columns = movie_stats.columns.droplevel()

In [15]:
# Creating a user-item matrix

from scipy.sparse import csr_matrix

def create_matrix(df):

    N = len(df['userId'].unique())
    M = len(df['movieId'].unique())

    user_mapper = dict(zip(np.unique(df['userId']), list(range(N))))
    movie_mapper = dict(zip(np.unique(df['movieId']), list(range(M))))

    user_inv_mapper = dict(zip(list(range(N)), np.unique(df['userId'])))
    movie_inv_mapper = dict(zip(list(range(M)), np.unique(df['movieId'])))

    user_index = [user_mapper[i] for i in df['userId']]
    movie_index = [movie_mapper[i] for i in df['movieId']]

    X = csr_matrix((df['rating'], (movie_index, user_index)), shape=(M, N))

    return X, user_mapper, movie_mapper, user_inv_mapper, movie_inv_mapper

X, user_mapper, movie_mapper, user_inv_mapper, movie_inv_mapper = create_matrix(ratings)

In [17]:
user_mapper

{1: 0,
 2: 1,
 3: 2,
 4: 3,
 5: 4,
 6: 5,
 7: 6,
 8: 7,
 9: 8,
 10: 9,
 11: 10,
 12: 11,
 13: 12,
 14: 13,
 15: 14,
 16: 15,
 17: 16,
 18: 17,
 19: 18,
 20: 19,
 21: 20,
 22: 21,
 23: 22,
 24: 23,
 25: 24,
 26: 25,
 27: 26,
 28: 27,
 29: 28,
 30: 29,
 31: 30,
 32: 31,
 33: 32,
 34: 33,
 35: 34,
 36: 35,
 37: 36,
 38: 37,
 39: 38,
 40: 39,
 41: 40,
 42: 41,
 43: 42,
 44: 43,
 45: 44,
 46: 45,
 47: 46,
 48: 47,
 49: 48,
 50: 49,
 51: 50,
 52: 51,
 53: 52,
 54: 53,
 55: 54,
 56: 55,
 57: 56,
 58: 57,
 59: 58,
 60: 59,
 61: 60,
 62: 61,
 63: 62,
 64: 63,
 65: 64,
 66: 65,
 67: 66,
 68: 67,
 69: 68,
 70: 69,
 71: 70,
 72: 71,
 73: 72,
 74: 73,
 75: 74,
 76: 75,
 77: 76,
 78: 77,
 79: 78,
 80: 79,
 81: 80,
 82: 81,
 83: 82,
 84: 83,
 85: 84,
 86: 85,
 87: 86,
 88: 87,
 89: 88,
 90: 89,
 91: 90,
 92: 91,
 93: 92,
 94: 93,
 95: 94,
 96: 95,
 97: 96,
 98: 97,
 99: 98,
 100: 99,
 101: 100,
 102: 101,
 103: 102,
 104: 103,
 105: 104,
 106: 105,
 107: 106,
 108: 107,
 109: 108,
 110: 109,
 111: 110,
 112: 111,
 113: 112,
 114: 113,
 115: 114,
 116: 115,
 117: 116,
 118: 117,
 119: 118,
 120: 119,
 121: 120,
 122: 121,
 123: 122,
 124: 123,
 125: 124,
 126: 125,
 127: 126,
 128: 127,
 129: 128,
 130: 129,
 131: 130,
 132: 131,
 133: 132,
 134: 133,
 135: 134,
 136: 135,
 137: 136,
 138: 137,
 139: 138,
 140: 139,
 141: 140,
 142: 141,
 143: 142,
 144: 143,
 145: 144,
 146: 145,
 147: 146,
 148: 147,
 149: 148,
 150: 149,
 151: 150,
 152: 151,
 153: 152,
 154: 153,
 155: 154,
 156: 155,
 157: 156,
 158: 157,
 159: 158,
 160: 159,
 161: 160,
 162: 161,
 163: 162,
 164: 163,
 165: 164,
 166: 165,
 167: 166,
 168: 167,
 169: 168,
 170: 169,
 171: 170,
 172: 171,
 173: 172,
 174: 173,
 175: 174,
 176: 175,
 177: 176,
 178: 177,
 179: 178,
 180: 179,
 181: 180,
 182: 181,
 183: 182,
 184: 183,
 185: 184,
 186: 185,
 187: 186,
 188: 187,
 189: 188,
 190: 189,
 191: 190,
 192: 191,
 193: 192,
 194: 193,
 195: 194,
 196: 195,
 197: 196,
 198: 197,
 199: 198,
 200: 199,
 201: 200,
 202: 201,
 203: 202,
 204: 203,
 205: 204,
 206: 205,
 207: 206,
 208: 207,
 209: 208,
 210: 209,
 211: 210,
 212: 211,
 213: 212,
 214: 213,
 215: 214,
 216: 215,
 217: 216,
 218: 217,
 219: 218,
 220: 219,
 221: 220,
 222: 221,
 223: 222,
 224: 223,
 225: 224,
 226: 225,
 227: 226,
 228: 227,
 229: 228,
 230: 229,
 231: 230,
 232: 231,
 233: 232,
 234: 233,
 235: 234,
 236: 235,
 237: 236,
 238: 237,
 239: 238,
 240: 239,
 241: 240,
 242: 241,
 243: 242,
 244: 243,
 245: 244,
 246: 245,
 247: 246,
 248: 247,
 249: 248,
 250: 249,
 251: 250,
 252: 251,
 253: 252,
 254: 253,
 255: 254,
 256: 255,
 257: 256,
 258: 257,
 259: 258,
 260: 259,
 261: 260,
 262: 261,
 263: 262,
 264: 263,
 265: 264,
 266: 265,
 267: 266,
 268: 267,
 269: 268,
 270: 269,
 271: 270,
 272: 271,
 273: 272,
 274: 273,
 275: 274,
 276: 275,
 277: 276,
 278: 277,
 279: 278,
 280: 279,
 281: 280,
 282: 281,
 283: 282,
 284: 283,
 285: 284,
 286: 285,
 287: 286,
 288: 287,
 289: 288,
 290: 289,
 291: 290,
 292: 291,
 293: 292,
 294: 293,
 295: 294,
 296: 295,
 297: 296,
 298: 297,
 299: 298,
 300: 299,
 301: 300,
 302: 301,
 303: 302,
 304: 303,
 305: 304,
 306: 305,
 307: 306,
 308: 307,
 309: 308,
 310: 309,
 311: 310,
 312: 311,
 313: 312,
 314: 313,
 315: 314,
 316: 315,
 317: 316,
 318: 317,
 319: 318,
 320: 319,
 321: 320,
 322: 321,
 323: 322,
 324: 323,
 325: 324,
 326: 325,
 327: 326,
 328: 327,
 329: 328,
 330: 329,
 331: 330,
 332: 331,
 333: 332,
 334: 333,
 335: 334,
 336: 335,
 337: 336,
 338: 337,
 339: 338,
 340: 339,
 341: 340,
 342: 341,
 343: 342,
 344: 343,
 345: 344,
 346: 345,
 347: 346,
 348: 347,
 349: 348,
 350: 349,
 351: 350,
 352: 351,
 353: 352,
 354: 353,
 355: 354,
 356: 355,
 357: 356,
 358: 357,
 359: 358,
 360: 359,
 361: 360,
 362: 361,
 363: 362,
 364: 363,
 365: 364,
 366: 365,
 367: 366,
 368: 367,
 369: 368,
 370: 369,
 371: 370,
 372: 371,
 373: 372,
 374: 373,
 375: 374,
 376: 375,
 377: 376,
 378: 377,
 379: 378,
 380: 379,
 381: 380,
 382: 381,
 383: 382,
 384: 383,
 385: 384,
 386: 385,
 387: 386,
 388: 387,
 389: 388,
 390: 389,
 391: 390,
 392: 391,
 393: 392,
 394: 393,
 395: 394,
 396: 395,
 397: 396,
 398: 397,
 399: 398,
 400: 399,
 401: 400,
 402: 401,
 403: 402,
 404: 403,
 405: 404,
 406: 405,
 407: 406,
 408: 407,
 409: 408,
 410: 409,
 411: 410,
 412: 411,
 413: 412,
 414: 413,
 415: 414,
 416: 415,
 417: 416,
 418: 417,
 419: 418,
 420: 419,
 421: 420,
 422: 421,
 423: 422,
 424: 423,
 425: 424,
 426: 425,
 427: 426,
 428: 427,
 429: 428,
 430: 429,
 431: 430,
 432: 431,
 433: 432,
 434: 433,
 435: 434,
 436: 435,
 437: 436,
 438: 437,
 439: 438,
 440: 439,
 441: 440,
 442: 441,
 443: 442,
 444: 443,
 445: 444,
 446: 445,
 447: 446,
 448: 447,
 449: 448,
 450: 449,
 451: 450,
 452: 451,
 453: 452,
 454: 453,
 455: 454,
 456: 455,
 457: 456,
 458: 457,
 459: 458,
 460: 459,
 461: 460,
 462: 461,
 463: 462,
 464: 463,
 465: 464,
 466: 465,
 467: 466,
 468: 467,
 469: 468,
 470: 469,
 471: 470,
 472: 471,
 473: 472,
 474: 473,
 475: 474,
 476: 475,
 477: 476,
 478: 477,
 479: 478,
 480: 479,
 481: 480,
 482: 481,
 483: 482,
 484: 483,
 485: 484,
 486: 485,
 487: 486,
 488: 487,
 489: 488,
 490: 489,
 491: 490,
 492: 491,
 493: 492,
 494: 493,
 495: 494,
 496: 495,
 497: 496,
 498: 497,
 499: 498,
 500: 499,
 501: 500,
 502: 501,
 503: 502,
 504: 503,
 505: 504,
 506: 505,
 507: 506,
 508: 507,
 509: 508,
 510: 509,
 511: 510,
 512: 511,
 513: 512,
 514: 513,
 515: 514,
 516: 515,
 517: 516,
 518: 517,
 519: 518,
 520: 519,
 521: 520,
 522: 521,
 523: 522,
 524: 523,
 525: 524,
 526: 525,
 527: 526,
 528: 527,
 529: 528,
 530: 529,
 531: 530,
 532: 531,
 533: 532,
 534: 533,
 535: 534,
 536: 535,
 537: 536,
 538: 537,
 539: 538,
 540: 539,
 541: 540,
 542: 541,
 543: 542,
 544: 543,
 545: 544,
 546: 545,
 547: 546,
 548: 547,
 549: 548,
 550: 549,
 551: 550,
 552: 551,
 553: 552,
 554: 553,
 555: 554,
 556: 555,
 557: 556,
 558: 557,
 559: 558,
 560: 559,
 561: 560,
 562: 561,
 563: 562,
 564: 563,
 565: 564,
 566: 565,
 567: 566,
 568: 567,
 569: 568,
 570: 569,
 571: 570,
 572: 571,
 573: 572,
 574: 573,
 575: 574,
 576: 575,
 577: 576,
 578: 577,
 579: 578,
 580: 579,
 581: 580,
 582: 581,
 583: 582,
 584: 583,
 585: 584,
 586: 585,
 587: 586,
 588: 587,
 589: 588,
 590: 589,
 591: 590,
 592: 591,
 593: 592,
 594: 593,
 595: 594,
 596: 595,
 597: 596,
 598: 597,
 599: 598,
 600: 599,
 601: 600,
 602: 601,
 603: 602,
 604: 603,
 605: 604,
 606: 605,
 607: 606,
 608: 607,
 609: 608,
 610: 609}

In [21]:
# Finding Similar movies using kNN

from sklearn.neighbors import NearestNeighbors

def find_similar_movies(movie_id, X, k, metric='cosine', show_distance=False):
    neighbour_ids = []

    movie_ind = movie_mapper[movie_id]
    movie_vec = X[movie_ind]
    k+=1
    kNN = NearestNeighbors(n_neighbors=k, algorithm="brute", metric=metric)
    kNN.fit(X)

    movie_vec = movie_vec.reshape(1, -1)
    neighbour = kNN.kneighbors(movie_vec, return_distance=show_distance)

    for i in range(0, k):
        n= neighbour.item(i)
        neighbour_ids.append(movie_inv_mapper[n])
    neighbour_ids.pop(0)
    return neighbour_ids

movie_titles = dict(zip(movies['movieId'], movies['title']))

movie_id = 3

similar_ids = find_similar_movies(movie_id, X, k=10)
movie_title = movie_titles[movie_id]

print(f"Since you watched '{movie_title}', here are some recommendations for you:")
for i in similar_ids:
    print(movie_titles[i])

Since you watched 'Grumpier Old Men (1995)', here are some recommendations for you:
Grumpy Old Men (1993)
Striptease (1996)
Nutty Professor, The (1996)
Twister (1996)
Father of the Bride Part II (1995)
Broken Arrow (1996)
Bio-Dome (1996)
Truth About Cats & Dogs, The (1996)
Sabrina (1995)
Birdcage, The (1996)

In [24]:
# Movie Recommendations on the basis of user preferences

def recommend_movies_for_users(user_id, X, user_mapper, movie_mapper, movie_inv_mapper, k=10):

    df1 = ratings[ratings['userId'] == user_id]

    if df1.empty:
        print(f"User with ID {user_id} does not exist.")
        return
    
    movie_id = df1[df1['rating'] == max(df1['rating'])]['movieId'].iloc[0]

    movie_titles = dict(zip(movies['movieId'], movies['title']))

    similar_ids = find_similar_movies(movie_id, X, k)
    movie_title = movie_titles.get(movie_id, "Movie not found")

    if movie_title == 'Movie not found':
        print(f'Movie with ID {movie_id} not found.')
        return
    
    print(f'Since you watched {movie_title}, you might also like: ')

    for i in similar_ids:
        print(movie_titles.get(i, "Movie not found"))

In [25]:
user_id = 150
recommend_movies_for_users(user_id, X, user_mapper, movie_mapper, movie_inv_mapper, k=10)

Since you watched Twelve Monkeys (a.k.a. 12 Monkeys) (1995), you might also like:
Pulp Fiction (1994)
Terminator 2: Judgment Day (1991)
Independence Day (a.k.a. ID4) (1996)
Seven (a.k.a. Se7en) (1995)
Fargo (1996)
Fugitive, The (1993)
Usual Suspects, The (1995)
Jurassic Park (1993)
Star Wars: Episode IV - A New Hope (1977)
Heat (1995)

In [26]:
X

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 100836 stored elements and shape (9724, 610)>